server:
  port: 8080
spring:
  mail:
    host: smtp.qq.com
    username: 761676263
    password: dwsjeomddulpbdjd
    port: 465
    protocol: smtp
    enableEmail: false
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  main:
    allow-bean-definition-overriding: true
  resources:
    static-locations: classpath:/testStatic/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    view:
      suffix: .html
  thymeleaf:
    cache: false
  redis:
    password: A63631234
    database: 0
    timeout: 60000
    host: 127.0.0.1
    port: 6379
    #开启集群版至少要三主三从
    #cluster:
      #nodes:
      #max-redirects:
    lettuce:
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 60000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  datasource:
    url: jdbc:mysql://127.0.0.1:8066/forum?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      concurrency: 2
      max-concurrency: 2
      simple:
        retry:
          enabled: true
          max-attempts: 5 #最大重试次数
          initial-interval: 2000 #重试间隔时间（单位毫秒）
          max-interval: 1200000 #重试最大时间间隔（单位毫秒）
          multiplier: 5 #应用于前一重试间隔的乘法器。
        default-requeue-rejected: false
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径 type-aliases-package: com.winter.model # 注意：对应实体类的路径
  configuration:
    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true
loggin:
  config: classpath:config/log/logback-spring.xml
  path: classpath:log


